DROP TABLE IF EXISTS url;

CREATE TABLE urls (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  vanity TEXT UNIQUE NOT NULL,
  url TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  visit_count INTEGER DEFAULT 0
);