"""empty message

Revision ID: 2d3fd3b013f4
Revises: ed69a26bebbe
Create Date: 2022-02-27 16:17:41.435362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3fd3b013f4'
down_revision = 'ed69a26bebbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('last_visited', sa.DateTime(), nullable=True))
    op.drop_column('URL', 'last_visted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('last_visted', sa.DATETIME(), nullable=True))
    op.drop_column('URL', 'last_visited')
    # ### end Alembic commands ###
