"""empty message

Revision ID: 36772f67d5f0
Revises: 
Create Date: 2022-01-11 19:29:41.527717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36772f67d5f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vanity', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_URL_vanity'), 'URL', ['vanity'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_URL_vanity'), table_name='URL')
    op.drop_table('URL')
    # ### end Alembic commands ###
